# Generated by Django 5.2.17 on 2026-08-29 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.UUIDField()),
                ('platform', models.CharField(max_length=64)),
                ('client_version', models.CharField(max_length=64)),
                ('report_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('counter_epoch', models.UUIDField(default=uuid.uuid4)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('quiescent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('project__name', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('attention_state', models.CharField(default='unknown', max_length=32)),
                ('current_state', models.JSONField(default=dict)),
                ('state_schema_version', models.PositiveSmallIntegerField(default=1)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-last_seen', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AppServerAggregate',
            fields=[
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='app_server', serialize=False, to='fleet.instance')),
                ('counter_epoch', models.UUIDField()),
                ('enabled', models.BooleanField(default=False)),
                ('availability_state', models.CharField(default='unknown', max_length=32)),
                ('attempts', models.PositiveBigIntegerField(default=0)),
                ('failures', models.PositiveBigIntegerField(default=0)),
                ('fallbacks', models.PositiveBigIntegerField(default=0)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('client_version', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_external_id', models.UUIDField()),
                ('project_name', models.CharField(max_length=160)),
                ('instance_external_id', models.UUIDField()),
                ('platform', models.CharField(max_length=64)),
                ('client_version', models.CharField(max_length=64)),
                ('user_code', models.CharField(max_length=12, unique=True)),
                ('device_secret_digest', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('issued', 'Issued')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issued_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.instance')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='IngestReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('sequence', models.PositiveBigIntegerField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='fleet.instance')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='MaterialEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_kind', models.CharField(max_length=64)),
                ('summary_code', models.CharField(max_length=96)),
                ('occurred_at', models.DateTimeField()),
                ('retained_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_events', to='fleet.instance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_events', to='fleet.project')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='fleet.project'),
        ),
        migrations.CreateModel(
            name='ReporterCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_prefix', models.CharField(db_index=True, max_length=12)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='fleet.instance')),
            ],
        ),
        migrations.CreateModel(
            name='WorkEfficiencyAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter_epoch', models.UUIDField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('remedial_tokens_actual', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remedial_token_coverage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('remedial_interactions', models.PositiveBigIntegerField(default=0)),
                ('remedial_output_bytes', models.PositiveBigIntegerField(default=0)),
                ('remedial_duration_ms', models.PositiveBigIntegerField(default=0)),
                ('remedial_retries', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_efficiency', to='fleet.instance')),
            ],
            options={
                'ordering': ('-window_end',),
            },
        ),
        migrations.CreateModel(
            name='FailureGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('retained_until', models.DateTimeField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_groups', to='fleet.instance')),
            ],
            options={
                'ordering': ('-last_seen',),
                'constraints': [models.UniqueConstraint(fields=('instance', 'signature'), name='unique_instance_failure_signature')],
            },
        ),
        migrations.AddConstraint(
            model_name='instance',
            constraint=models.UniqueConstraint(fields=('project', 'external_id'), name='unique_project_instance'),
        ),
        migrations.AddConstraint(
            model_name='workefficiencyaggregate',
            constraint=models.UniqueConstraint(fields=('instance', 'counter_epoch', 'window_start', 'window_end'), name='unique_instance_efficiency_window'),
        ),
    ]
