# Generated by Django 5.2.17 on 2026-08-30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("fleet", "0001_initial")]

    operations = [
        migrations.AddField(model_name="instance", name="work_inventory_digest", field=models.CharField(blank=True, max_length=64)),
        migrations.AddField(model_name="instance", name="work_inventory_observed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="instance", name="work_inventory_sequence", field=models.PositiveBigIntegerField(default=0)),
        migrations.AddField(model_name="instance", name="work_inventory_total", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="instance", name="work_inventory_truncated", field=models.BooleanField(default=False)),
        migrations.CreateModel(
            name="WorkArtifactSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("artifact_external_id", models.UUIDField()),
                ("visible_id", models.CharField(max_length=64)),
                ("artifact_type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=160)),
                ("document_lifecycle", models.CharField(max_length=32)),
                ("outcome_lifecycle", models.CharField(default="unknown", max_length=32)),
                ("outcome_disposition", models.CharField(default="unknown", max_length=48)),
                ("reconciliation_state", models.CharField(default="unknown", max_length=32)),
                ("parent_ids", models.JSONField(default=list)),
                ("produces_ids", models.JSONField(default=list)),
                ("source_updated_at", models.DateTimeField()),
                ("observed_at", models.DateTimeField()),
                ("snapshot_sequence", models.PositiveBigIntegerField()),
                ("instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_artifacts", to="fleet.instance")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="work_artifacts", to="fleet.project")),
            ],
            options={"ordering": ("visible_id",)},
        ),
        migrations.CreateModel(
            name="LifecycleEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_key", models.CharField(max_length=64)),
                ("artifact_external_id", models.UUIDField()),
                ("visible_id", models.CharField(max_length=64)),
                ("artifact_type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=160)),
                ("transition", models.CharField(max_length=32)),
                ("from_state", models.CharField(max_length=48)),
                ("to_state", models.CharField(max_length=48)),
                ("occurred_at", models.DateTimeField()),
                ("retained_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_events", to="fleet.instance")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lifecycle_events", to="fleet.project")),
            ],
            options={"ordering": ("-occurred_at", "-created_at")},
        ),
        migrations.AddConstraint(model_name="workartifactsnapshot", constraint=models.UniqueConstraint(fields=("instance", "artifact_external_id"), name="unique_instance_work_artifact")),
        migrations.AddConstraint(model_name="lifecycleevent", constraint=models.UniqueConstraint(fields=("instance", "event_key"), name="unique_instance_lifecycle_event")),
    ]
