# Generated by Django 5.2.17 on 2026-08-30 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_work_lifecycle_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=48)),
                ('severity', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('current_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField()),
                ('last_changed', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('retained_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_conditions', to='fleet.instance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_conditions', to='fleet.project')),
            ],
            options={
                'ordering': ('-active', '-last_changed', 'reason_code'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('instance', 'reason_code'), name='unique_active_instance_attention_reason')],
            },
        ),
    ]
