# Generated by Django 5.2.17 on 2026-09-03 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_recursive_closure_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportercredential',
            name='scope',
            field=models.CharField(choices=[('operational', 'Operational'), ('qualification:write', 'Qualification write')], default='operational', max_length=32),
        ),
        migrations.CreateModel(
            name='QualificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(max_length=96, unique=True)),
                ('manifest_digest', models.CharField(max_length=64)),
                ('candidate_commit', models.CharField(max_length=40)),
                ('scenario_id', models.CharField(max_length=16)),
                ('platform', models.CharField(max_length=64)),
                ('environment', models.CharField(default='development', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('purged', 'Purged')], default='active', max_length=16)),
                ('manifest', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('purge_digest', models.CharField(blank=True, max_length=64)),
                ('purged_descendant_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'run_id'),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='qualification_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='fleet.qualificationrun'),
        ),
        migrations.AddField(
            model_name='reportercredential',
            name='qualification_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='fleet.qualificationrun'),
        ),
        migrations.AddConstraint(
            model_name='reportercredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qualification_run__isnull', True), ('scope', 'operational')), models.Q(('qualification_run__isnull', False), ('scope', 'qualification:write')), _connector='OR'), name='reporter_credential_scope_owner_valid'),
        ),
        migrations.AddConstraint(
            model_name='qualificationrun',
            constraint=models.CheckConstraint(condition=models.Q(('environment', 'development')), name='qualification_run_development_only'),
        ),
        migrations.AddConstraint(
            model_name='qualificationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purge_digest', ''), ('purged_at__isnull', True), ('status__in', ('active', 'expired'))), models.Q(('purged_at__isnull', False), ('status', 'purged')), _connector='OR'), name='qualification_run_purge_state_valid'),
        ),
    ]
