# Generated by Django 5.2.17 on 2026-09-04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0009_qualification_run_namespace"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoopFindingSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("finding_external_id", models.CharField(max_length=32)),
                ("category", models.CharField(max_length=48)),
                ("severity", models.CharField(max_length=16)),
                ("reason_code", models.CharField(max_length=64)),
                ("subject_visible_id", models.CharField(max_length=64)),
                ("observed_state", models.CharField(max_length=32)),
                ("expected_state", models.CharField(max_length=32)),
                ("state", models.CharField(max_length=16)),
                ("source_revision", models.PositiveBigIntegerField()),
                ("first_observed_at", models.DateTimeField()),
                ("last_observed_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("recurrence_count", models.PositiveIntegerField(default=0)),
                ("command", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField()),
                ("snapshot_sequence", models.PositiveBigIntegerField()),
                ("instance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="loop_findings", to="fleet.instance")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="loop_findings", to="fleet.project")),
            ],
            options={
                "ordering": ("-last_observed_at", "finding_external_id"),
            },
        ),
        migrations.AddConstraint(
            model_name="loopfindingsnapshot",
            constraint=models.UniqueConstraint(fields=("instance", "finding_external_id"), name="unique_instance_loop_finding"),
        ),
    ]
